### ISSUE TITLE
OpenFlow OpenWRT Binary for 

### ISSUE THREAD

**Issue by bachipeachy** [CPqD/openflow-openwrt#1]
Is there a binary for flashing TP-LINK TL-WR1043ND Router with OF 1.3 ?
If not, what trunk or preferably stable release of OpenWRT do I compile after adding OF 1.3 from this site  on the new hardware version 1.13?

**Comment by ederlf** [comment]
We don't have an available compiled image yet.
Please follow the instructions on this page  https://github.com/CPqD/ofsoftswitch13/wiki/OpenFlow-1.3-for-OpenWRT. You will see that we are using the latest backfire stable release.
